// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUlmHtN1Gz5QlJTqkj_Oa4TgnKI83ToYo',
    appId: '1:1028487279487:web:de50d9def0d2fcb9d5604a',
    messagingSenderId: '1028487279487',
    projectId: 'halimali-cs-project1',
    authDomain: 'halimali-cs-project1.firebaseapp.com',
    storageBucket: 'halimali-cs-project1.appspot.com',
    measurementId: 'G-E5HNQBPWXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC78JoMnPQxbN_QLVWZtCc8w_H9nj2kdRg',
    appId: '1:1028487279487:android:3bda0a4859893d66d5604a',
    messagingSenderId: '1028487279487',
    projectId: 'halimali-cs-project1',
    storageBucket: 'halimali-cs-project1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvCsUrMCydfz9y-4bjgvZGKRCHEY4qqss',
    appId: '1:1028487279487:ios:c10a85708805a257d5604a',
    messagingSenderId: '1028487279487',
    projectId: 'halimali-cs-project1',
    storageBucket: 'halimali-cs-project1.appspot.com',
    iosClientId: '1028487279487-gmqt3t8bmspubp27vj3082j7fnktka5f.apps.googleusercontent.com',
    iosBundleId: 'com.halimali.halimali',
  );
}
